### ISSUE TITLE
Error when enabling module localgov_directories_or

### ISSUE THREAD

**Issue by Boosmith** [localgovdrupal/localgov_directories#195]
Error below when enabling localgov_directories_or. This is with localgovdrupal v2.3.9 and Drupal version 9.3.12

```
lando drush en localgov_directories_or -y   
The following module(s) will be enabled: localgov_directories_or, localgov_openreferral, serialization, rest

 // Do you want to continue?: yes.                                                                                      

 [error]  Error: Call to undefined method Drupal\localgov_openreferral\Pager\PagerParametersDecorator::findAdaptiveKeys() in Drupal\pagerer\PagererManager->createPager() (line 59 of /app/web/modules/contrib/pagerer/src/PagererManager.php) #0 /app/web/core/lib/Drupal/Core/Entity/Query/QueryBase.php(313): Drupal\pagerer\PagererManager->createPager(6, 20, 0)
#1 /app/web/core/lib/Drupal/Core/Config/Entity/Query/Query.php(104): Drupal\Core\Entity\Query\QueryBase->initializePager()
#2 /app/web/modules/contrib/admin_toolbar/admin_toolbar_tools/src/Plugin/Derivative/ExtraLinks.php(104): Drupal\Core\Config\Entity\Query\Query->execute()
#3 /app/web/core/lib/Drupal/Component/Plugin/Discovery/DerivativeDiscoveryDecorator.php(101): Drupal\admin_toolbar_tools\Plugin\Derivative\ExtraLinks->getDerivativeDefinitions(Array)
#4 /app/web/core/lib/Drupal/Component/Plugin/Discovery/DerivativeDiscoveryDecorator.php(87): Drupal\Component\Plugin\Discovery\DerivativeDiscoveryDecorator->getDerivatives(Array)
#5 /app/web/core/lib/Drupal/Core/Menu/MenuLinkManager.php(164): Drupal\Component\Plugin\Discovery\DerivativeDiscoveryDecorator->getDefinitions()
#6 /app/web/core/lib/Drupal/Core/Menu/MenuLinkManager.php(189): Drupal\Core\Menu\MenuLinkManager->getDefinitions()
#7 /app/web/core/lib/Drupal/Core/EventSubscriber/MenuRouterRebuildSubscriber.php(82): Drupal\Core\Menu\MenuLinkManager->rebuild()
#8 /app/web/core/lib/Drupal/Core/EventSubscriber/MenuRouterRebuildSubscriber.php(70): Drupal\Core\EventSubscriber\MenuRouterRebuildSubscriber->menuLinksRebuild()
#9 [internal function]: Drupal\Core\EventSubscriber\MenuRouterRebuildSubscriber->onRouterRebuild(Object(Drupal\Component\EventDispatcher\Event), 'routing.route_f...', Object(Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher))
#10 /app/web/core/lib/Drupal/Component/EventDispatcher/ContainerAwareEventDispatcher.php(142): call_user_func(Array, Object(Drupal\Component\EventDispatcher\Event), 'routing.route_f...', Object(Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher))
#11 /app/web/core/lib/Drupal/Core/Routing/RouteBuilder.php(197): Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher->dispatch(Object(Drupal\Component\EventDispatcher\Event), 'routing.route_f...')
#12 /app/web/core/lib/Drupal/Core/ProxyClass/Routing/RouteBuilder.php(83): Drupal\Core\Routing\RouteBuilder->rebuild()
#13 /app/web/core/lib/Drupal/Core/Extension/ModuleInstaller.php(382): Drupal\Core\ProxyClass\Routing\RouteBuilder->rebuild()
#14 /app/web/core/lib/Drupal/Core/ProxyClass/Extension/ModuleInstaller.php(83): Drupal\Core\Extension\ModuleInstaller->install(Array, true)
#15 /app/vendor/drush/drush/src/Drupal/Commands/pm/PmCommands.php(103): Drupal\Core\ProxyClass\Extension\ModuleInstaller->install(Array, true)
#16 [internal function]: Drush\Drupal\Commands\pm\PmCommands->enable(Array, Array)
#17 /app/vendor/consolidation/annotated-command/src/CommandProcessor.php(257): call_user_func_array(Array, Array)
#18 /app/vendor/consolidation/annotated-command/src/CommandProcessor.php(212): Consolidation\AnnotatedCommand\CommandProcessor->runCommandCallback(Array, Object(Consolidation\AnnotatedCommand\CommandData))
#19 /app/vendor/consolidation/annotated-command/src/CommandProcessor.php(176): Consolidation\AnnotatedCommand\CommandProcessor->validateRunAndAlter(Array, Array, Object(Consolidation\AnnotatedCommand\CommandData))
#20 /app/vendor/consolidation/annotated-command/src/AnnotatedCommand.php(350): Consolidation\AnnotatedCommand\CommandProcessor->process(Object(Symfony\Component\Console\Output\ConsoleOutput), Array, Array, Object(Consolidation\AnnotatedCommand\CommandData))
#21 /app/vendor/symfony/console/Command/Command.php(255): Consolidation\AnnotatedCommand\AnnotatedCommand->execute(Object(Drush\Symfony\DrushArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#22 /app/vendor/symfony/console/Application.php(1027): Symfony\Component\Console\Command\Command->run(Object(Drush\Symfony\DrushArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#23 /app/vendor/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand(Object(Consolidation\AnnotatedCommand\AnnotatedCommand), Object(Drush\Symfony\DrushArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#24 /app/vendor/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun(Object(Drush\Symfony\DrushArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#25 /app/vendor/drush/drush/src/Runtime/Runtime.php(118): Symfony\Component\Console\Application->run(Object(Drush\Symfony\DrushArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#26 /app/vendor/drush/drush/src/Runtime/Runtime.php(48): Drush\Runtime\Runtime->doRun(Array, Object(Symfony\Component\Console\Output\ConsoleOutput))
#27 /app/vendor/drush/drush/drush.php(72): Drush\Runtime\Runtime->run(Array)
#28 /app/vendor/drush/drush/drush(4): require('/app/vendor/dru...')
#29 {main}. 
Error: Call to undefined method Drupal\localgov_openreferral\Pager\PagerParametersDecorator::findAdaptiveKeys() in /app/web/modules/contrib/pagerer/src/PagererManager.php on line 59 #0 /app/web/core/lib/Drupal/Core/Entity/Query/QueryBase.php(313): Drupal\pagerer\PagererManager->createPager(6, 20, 0)
#1 /app/web/core/lib/Drupal/Core/Config/Entity/Query/Query.php(104): Drupal\Core\Entity\Query\QueryBase->initializePager()
#2 /app/web/modules/contrib/admin_toolbar/admin_toolbar_tools/src/Plugin/Derivative/ExtraLinks.php(104): Drupal\Core\Config\Entity\Query\Query->execute()
#3 /app/web/core/lib/Drupal/Component/Plugin/Discovery/DerivativeDiscoveryDecorator.php(101): Drupal\admin_toolbar_tools\Plugin\Derivative\ExtraLinks->getDerivativeDefinitions(Array)
#4 /app/web/core/lib/Drupal/Component/Plugin/Discovery/DerivativeDiscoveryDecorator.php(87): Drupal\Component\Plugin\Discovery\DerivativeDiscoveryDecorator->getDerivatives(Array)
#5 /app/web/core/lib/Drupal/Core/Menu/MenuLinkManager.php(164): Drupal\Component\Plugin\Discovery\DerivativeDiscoveryDecorator->getDefinitions()
#6 /app/web/core/lib/Drupal/Core/Menu/MenuLinkManager.php(189): Drupal\Core\Menu\MenuLinkManager->getDefinitions()
#7 /app/web/core/lib/Drupal/Core/EventSubscriber/MenuRouterRebuildSubscriber.php(82): Drupal\Core\Menu\MenuLinkManager->rebuild()
#8 /app/web/core/lib/Drupal/Core/EventSubscriber/MenuRouterRebuildSubscriber.php(70): Drupal\Core\EventSubscriber\MenuRouterRebuildSubscriber->menuLinksRebuild()
#9 [internal function]: Drupal\Core\EventSubscriber\MenuRouterRebuildSubscriber->onRouterRebuild(Object(Drupal\Component\EventDispatcher\Event), 'routing.route_f...', Object(Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher))
#10 /app/web/core/lib/Drupal/Component/EventDispatcher/ContainerAwareEventDispatcher.php(142): call_user_func(Array, Object(Drupal\Component\EventDispatcher\Event), 'routing.route_f...', Object(Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher))
#11 /app/web/core/lib/Drupal/Core/Routing/RouteBuilder.php(197): Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher->dispatch(Object(Drupal\Component\EventDispatcher\Event), 'routing.route_f...')
#12 /app/web/core/lib/Drupal/Core/ProxyClass/Routing/RouteBuilder.php(83): Drupal\Core\Routing\RouteBuilder->rebuild()
#13 /app/web/core/lib/Drupal/Core/Extension/ModuleInstaller.php(382): Drupal\Core\ProxyClass\Routing\RouteBuilder->rebuild()
#14 /app/web/core/lib/Drupal/Core/ProxyClass/Extension/ModuleInstaller.php(83): Drupal\Core\Extension\ModuleInstaller->install(Array, true)
#15 /app/vendor/drush/drush/src/Drupal/Commands/pm/PmCommands.php(103): Drupal\Core\ProxyClass\Extension\ModuleInstaller->install(Array, true)
#16 [internal function]: Drush\Drupal\Commands\pm\PmCommands->enable(Array, Array)
#17 /app/vendor/consolidation/annotated-command/src/CommandProcessor.php(257): call_user_func_array(Array, Array)
#18 /app/vendor/consolidation/annotated-command/src/CommandProcessor.php(212): Consolidation\AnnotatedCommand\CommandProcessor->runCommandCallback(Array, Object(Consolidation\AnnotatedCommand\CommandData))
#19 /app/vendor/consolidation/annotated-command/src/CommandProcessor.php(176): Consolidation\AnnotatedCommand\CommandProcessor->validateRunAndAlter(Array, Array, Object(Consolidation\AnnotatedCommand\CommandData))
#20 /app/vendor/consolidation/annotated-command/src/AnnotatedCommand.php(350): Consolidation\AnnotatedCommand\CommandProcessor->process(Object(Symfony\Component\Console\Output\ConsoleOutput), Array, Array, Object(Consolidation\AnnotatedCommand\CommandData))
#21 /app/vendor/symfony/console/Command/Command.php(255): Consolidation\AnnotatedCommand\AnnotatedCommand->execute(Object(Drush\Symfony\DrushArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#22 /app/vendor/symfony/console/Application.php(1027): Symfony\Component\Console\Command\Command->run(Object(Drush\Symfony\DrushArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#23 /app/vendor/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand(Object(Consolidation\AnnotatedCommand\AnnotatedCommand), Object(Drush\Symfony\DrushArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#24 /app/vendor/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun(Object(Drush\Symfony\DrushArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#25 /app/vendor/drush/drush/src/Runtime/Runtime.php(118): Symfony\Component\Console\Application->run(Object(Drush\Symfony\DrushArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#26 /app/vendor/drush/drush/src/Runtime/Runtime.php(48): Drush\Runtime\Runtime->doRun(Array, Object(Symfony\Component\Console\Output\ConsoleOutput))
#27 /app/vendor/drush/drush/drush.php(72): Drush\Runtime\Runtime->run(Array)
#28 /app/vendor/drush/drush/drush(4): require('/app/vendor/dru...')
#29 {main}
Error: Call to undefined method Drupal\localgov_openreferral\Pager\PagerParametersDecorator::findAdaptiveKeys() in Drupal\pagerer\PagererManager->createPager() (line 59 of /app/web/modules/contrib/pagerer/src/PagererManager.php).
```

**Comment by ekes** [comment]
Hmm... that seems to be something to do with a module 'pagerer'?
It's calling a method `findAdaptiveKeys` that doesn't exist on the [PagerParametersInterface](https://api.drupal.org/api/drupal/core%21lib%21Drupal%21Core%21Pager%21PagerParametersInterface.php/interface/PagerParametersInterface/9.4.x) in line 59 of `pagerer/src/PagererManager.php`

**Comment by ekes** [comment]
I fear that module might be a bit overreaching. If I understand it
https://git.drupalcode.org/project/pagerer/-/blob/8.x-2.x/src/PagererServiceProvider.php
puts its pager onto _*all*_ pagers which here is not desired.

So unless I'm misunderstanding I think you need to fix that module not to inject itself onto pagers that it doesn't fit.

**Comment by Boosmith** [comment]
Ok, thanks. Pagerer is a contrib module so we'll look to see if we can remove it. FYI after I uinstalled pagerer, localgov_directories_or seemed to install fine
