### ISSUE TITLE
Errors when installing site from existing configuration

### ISSUE THREAD

**Issue by siliconmeadow** [localgovdrupal/localgov_directories#244]
I have been trying to create a site from existing configuration for aid in our CI/CD processes, but am getting fatal errors with both the `localgov_directories_page` module and the `localgov_directories_org` module.

__Note:__ I've been using the patch from [issue 2982052 comment #80](https://www.drupal.org/files/issues/2022-05-19/2982052-80.patch) to allow config from a profile which contains an install hook to be used for site installation.

Here is a rough outline of what I've done:

## From config on a site which has had the `localgov_demo` module installed (_the kitchen sink_ version)

1. `ddev drush si localgov` /** success **/
2. `drush en localgov_demo` /** success **/
3. `drush cex` /** success */
4. `drush si --existing config`

Failure: 
```
 [notice] Starting Drupal installation. This takes a while.
 [notice] Performed install task: install_select_language
 [notice] Performed install task: install_select_profile
 [notice] Performed install task: install_load_profile
 [notice] Performed install task: install_verify_requirements
 [notice] Performed install task: install_verify_database_ready
 [notice] Performed install task: install_base_system
 [notice] Performed install task: install_bootstrap_full

In EntityType.php line 877:

  Missing bundle entity, entity type node_type, entity id localgov_directories_page.


Failed to run drush si --existing-config: exit status 1
```

## From config on a site with `localgov_directories` module enabled only

1. `ddev drush si localgov` /** success **/
2. `drush en localgov_directories` /** success **/
3. `drush cex` /** success **/
4. `drush si --existing config` /** success **/

## From config on a site with `localgov_directories`, `localgov_search` and `localgov_directories_db` enabled

I added `localgov_search` and `localgov_directories_db` as when I'd tried to install from a config that had `localgov_directories_page` installed, the messages seemed to be search index related (more on that later).

1. `ddev drush si localgov` /** success **/
2. `drush en localgov_directories localgov_search localgov_directories_db` /** success **/
3. `drush cex` /** success **/
4.  `drush si --existing config` /** success **/

## From config on a site with `localgov_directories`, `localgov_search`, `localgov_directories_db` and `localgov_directories_page` enabled

1. `ddev drush si localgov` /** success **/
2. `drush en localgov_directories localgov_search localgov_directories_db` /** success **/
3. `drush cex` /** success **/
4. `drush si --existing config`

Failure:
<details><summary>Could have been in a gist, I guess, but click here</summary>
<p>

```
[notice] Starting Drupal installation. This takes a while.
 [notice] Performed install task: install_select_language
 [notice] Performed install task: install_select_profile
 [notice] Performed install task: install_load_profile
 [notice] Performed install task: install_verify_requirements
 [notice] Performed install task: install_verify_database_ready
 [notice] Performed install task: install_base_system
 [notice] Performed install task: install_bootstrap_full
 [error]  TypeError: Drupal\localgov_directories\ConfigurationHelper::getIndex(): Return value must be of type Drupal\search_api\IndexInterface, null returned in Drupal\localgov_directories\ConfigurationHelper->getIndex() (line 128 of /var/www/html/web/modules/contrib/localgov_directories/src/ConfigurationHelper.php) #0 /var/www/html/web/modules/contrib/localgov_directories/src/ConfigurationHelper.php(197): Drupal\localgov_directories\ConfigurationHelper->getIndex()
#1 /var/www/html/web/modules/contrib/localgov_directories/localgov_directories.module(155): Drupal\localgov_directories\ConfigurationHelper->insertedTitleSortField(Object(Drupal\field\Entity\FieldConfig))
#2 [internal function]: localgov_directories_field_config_insert(Object(Drupal\field\Entity\FieldConfig))
#3 /var/www/html/web/core/lib/Drupal/Core/Extension/ModuleHandler.php(426): call_user_func_array(Object(Closure), Array)
#4 /var/www/html/web/core/lib/Drupal/Core/Extension/ModuleHandler.php(405): Drupal\Core\Extension\ModuleHandler->Drupal\Core\Extension\{closure}(Object(Closure), 'localgov_direct...')
#5 /var/www/html/web/core/lib/Drupal/Core/Extension/ModuleHandler.php(433): Drupal\Core\Extension\ModuleHandler->invokeAllWith('field_config_in...', Object(Closure))
#6 /var/www/html/web/core/lib/Drupal/Core/Config/Entity/ConfigEntityStorage.php(337): Drupal\Core\Extension\ModuleHandler->invokeAll('field_config_in...', Array)
#7 /var/www/html/web/core/lib/Drupal/Core/Entity/EntityStorageBase.php(598): Drupal\Core\Config\Entity\ConfigEntityStorage->invokeHook('insert', Object(Drupal\field\Entity\FieldConfig))
#8 /var/www/html/web/core/lib/Drupal/Core/Entity/EntityStorageBase.php(523): Drupal\Core\Entity\EntityStorageBase->doPostSave(Object(Drupal\field\Entity\FieldConfig), false)
#9 /var/www/html/web/core/lib/Drupal/Core/Config/Entity/ConfigEntityStorage.php(253): Drupal\Core\Entity\EntityStorageBase->save(Object(Drupal\field\Entity\FieldConfig))
#10 /var/www/html/web/core/lib/Drupal/Core/Entity/EntityBase.php(339): Drupal\Core\Config\Entity\ConfigEntityStorage->save(Object(Drupal\field\Entity\FieldConfig))
#11 /var/www/html/web/core/lib/Drupal/Core/Config/Entity/ConfigEntityBase.php(607): Drupal\Core\Entity\EntityBase->save()
#12 /var/www/html/web/core/lib/Drupal/Core/Config/Entity/ConfigEntityStorage.php(354): Drupal\Core\Config\Entity\ConfigEntityBase->save()
#13 /var/www/html/web/core/lib/Drupal/Core/Config/ConfigImporter.php(1001): Drupal\Core\Config\Entity\ConfigEntityStorage->importCreate('field.field.nod...', Object(Drupal\Core\Config\Config), Object(Drupal\Core\Config\Config))
#14 /var/www/html/web/core/lib/Drupal/Core/Config/ConfigImporter.php(787): Drupal\Core\Config\ConfigImporter->importInvokeOwner('', 'create', 'field.field.nod...')
#15 /var/www/html/web/core/lib/Drupal/Core/Config/ConfigImporter.php(608): Drupal\Core\Config\ConfigImporter->processConfiguration('', 'create', 'field.field.nod...')
#16 /var/www/html/web/core/lib/Drupal/Core/Config/ConfigImporter.php(512): Drupal\Core\Config\ConfigImporter->processConfigurations(Array)
#17 /var/www/html/web/core/lib/Drupal/Core/Config/Importer/ConfigImporterBatch.php(31): Drupal\Core\Config\ConfigImporter->doSyncStep('processConfigur...', Array)
#18 /var/www/html/web/core/includes/batch.inc(295): Drupal\Core\Config\Importer\ConfigImporterBatch::process(Object(Drupal\Core\Config\ConfigImporter), 'processConfigur...', Array)
#19 /var/www/html/web/core/includes/form.inc(955): _batch_process()
#20 /var/www/html/web/core/includes/install.core.inc(653): batch_process(Object(Drupal\Core\Url), Object(Drupal\Core\Url))
#21 /var/www/html/web/core/includes/install.core.inc(571): install_run_task(Array, Array)
#22 /var/www/html/web/core/includes/install.core.inc(119): install_run_tasks(Array, Array)
#23 /var/www/html/vendor/drush/drush/includes/drush.inc(129): install_drupal(Object(Composer\Autoload\ClassLoader), Array, Array)
#24 /var/www/html/vendor/drush/drush/includes/drush.inc(113): drush_call_user_func_array('install_drupal', Array)
#25 /var/www/html/vendor/drush/drush/src/Commands/core/SiteInstallCommands.php(152): drush_op('install_drupal', Object(Composer\Autoload\ClassLoader), Array, Array)
#26 [internal function]: Drush\Commands\core\SiteInstallCommands->install('localgov', Array)
#27 /var/www/html/vendor/consolidation/annotated-command/src/CommandProcessor.php(257): call_user_func_array(Array, Array)
#28 /var/www/html/vendor/consolidation/annotated-command/src/CommandProcessor.php(212): Consolidation\AnnotatedCommand\CommandProcessor->runCommandCallback(Array, Object(Consolidation\AnnotatedCommand\CommandData))
#29 /var/www/html/vendor/consolidation/annotated-command/src/CommandProcessor.php(176): Consolidation\AnnotatedCommand\CommandProcessor->validateRunAndAlter(Array, Array, Object(Consolidation\AnnotatedCommand\CommandData))
#30 /var/www/html/vendor/consolidation/annotated-command/src/AnnotatedCommand.php(350): Consolidation\AnnotatedCommand\CommandProcessor->process(Object(Symfony\Component\Console\Output\ConsoleOutput), Array, Array, Object(Consolidation\AnnotatedCommand\CommandData))
#31 /var/www/html/vendor/symfony/console/Command/Command.php(255): Consolidation\AnnotatedCommand\AnnotatedCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#32 /var/www/html/vendor/symfony/console/Application.php(1027): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#33 /var/www/html/vendor/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand(Object(Consolidation\AnnotatedCommand\AnnotatedCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#34 /var/www/html/vendor/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#35 /var/www/html/vendor/drush/drush/src/Runtime/Runtime.php(124): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#36 /var/www/html/vendor/drush/drush/src/Runtime/Runtime.php(51): Drush\Runtime\Runtime->doRun(Array, Object(Symfony\Component\Console\Output\ConsoleOutput))
#37 /var/www/html/vendor/drush/drush/drush.php(77): Drush\Runtime\Runtime->run(Array)
#38 /var/www/html/vendor/drush/drush/drush(4): require('/var/www/html/v...')
#39 /var/www/html/bin/drush(120): include('/var/www/html/v...')
#40 {main}.
TypeError: Drupal\localgov_directories\ConfigurationHelper::getIndex(): Return value must be of type Drupal\search_api\IndexInterface, null returned in /var/www/html/web/modules/contrib/localgov_directories/src/ConfigurationHelper.php on line 128 #0 /var/www/html/web/modules/contrib/localgov_directories/src/ConfigurationHelper.php(197): Drupal\localgov_directories\ConfigurationHelper->getIndex()
#1 /var/www/html/web/modules/contrib/localgov_directories/localgov_directories.module(155): Drupal\localgov_directories\ConfigurationHelper->insertedTitleSortField(Object(Drupal\field\Entity\FieldConfig))
#2 [internal function]: localgov_directories_field_config_insert(Object(Drupal\field\Entity\FieldConfig))
#3 /var/www/html/web/core/lib/Drupal/Core/Extension/ModuleHandler.php(426): call_user_func_array(Object(Closure), Array)
#4 /var/www/html/web/core/lib/Drupal/Core/Extension/ModuleHandler.php(405): Drupal\Core\Extension\ModuleHandler->Drupal\Core\Extension\{closure}(Object(Closure), 'localgov_direct...')
#5 /var/www/html/web/core/lib/Drupal/Core/Extension/ModuleHandler.php(433): Drupal\Core\Extension\ModuleHandler->invokeAllWith('field_config_in...', Object(Closure))
#6 /var/www/html/web/core/lib/Drupal/Core/Config/Entity/ConfigEntityStorage.php(337): Drupal\Core\Extension\ModuleHandler->invokeAll('field_config_in...', Array)
#7 /var/www/html/web/core/lib/Drupal/Core/Entity/EntityStorageBase.php(598): Drupal\Core\Config\Entity\ConfigEntityStorage->invokeHook('insert', Object(Drupal\field\Entity\FieldConfig))
#8 /var/www/html/web/core/lib/Drupal/Core/Entity/EntityStorageBase.php(523): Drupal\Core\Entity\EntityStorageBase->doPostSave(Object(Drupal\field\Entity\FieldConfig), false)
#9 /var/www/html/web/core/lib/Drupal/Core/Config/Entity/ConfigEntityStorage.php(253): Drupal\Core\Entity\EntityStorageBase->save(Object(Drupal\field\Entity\FieldConfig))
#10 /var/www/html/web/core/lib/Drupal/Core/Entity/EntityBase.php(339): Drupal\Core\Config\Entity\ConfigEntityStorage->save(Object(Drupal\field\Entity\FieldConfig))
#11 /var/www/html/web/core/lib/Drupal/Core/Config/Entity/ConfigEntityBase.php(607): Drupal\Core\Entity\EntityBase->save()
#12 /var/www/html/web/core/lib/Drupal/Core/Config/Entity/ConfigEntityStorage.php(354): Drupal\Core\Config\Entity\ConfigEntityBase->save()
#13 /var/www/html/web/core/lib/Drupal/Core/Config/ConfigImporter.php(1001): Drupal\Core\Config\Entity\ConfigEntityStorage->importCreate('field.field.nod...', Object(Drupal\Core\Config\Config), Object(Drupal\Core\Config\Config))
#14 /var/www/html/web/core/lib/Drupal/Core/Config/ConfigImporter.php(787): Drupal\Core\Config\ConfigImporter->importInvokeOwner('', 'create', 'field.field.nod...')
#15 /var/www/html/web/core/lib/Drupal/Core/Config/ConfigImporter.php(608): Drupal\Core\Config\ConfigImporter->processConfiguration('', 'create', 'field.field.nod...')
#16 /var/www/html/web/core/lib/Drupal/Core/Config/ConfigImporter.php(512): Drupal\Core\Config\ConfigImporter->processConfigurations(Array)
#17 /var/www/html/web/core/lib/Drupal/Core/Config/Importer/ConfigImporterBatch.php(31): Drupal\Core\Config\ConfigImporter->doSyncStep('processConfigur...', Array)
#18 /var/www/html/web/core/includes/batch.inc(295): Drupal\Core\Config\Importer\ConfigImporterBatch::process(Object(Drupal\Core\Config\ConfigImporter), 'processConfigur...', Array)
#19 /var/www/html/web/core/includes/form.inc(955): _batch_process()
#20 /var/www/html/web/core/includes/install.core.inc(653): batch_process(Object(Drupal\Core\Url), Object(Drupal\Core\Url))
#21 /var/www/html/web/core/includes/install.core.inc(571): install_run_task(Array, Array)
#22 /var/www/html/web/core/includes/install.core.inc(119): install_run_tasks(Array, Array)
#23 /var/www/html/vendor/drush/drush/includes/drush.inc(129): install_drupal(Object(Composer\Autoload\ClassLoader), Array, Array)
#24 /var/www/html/vendor/drush/drush/includes/drush.inc(113): drush_call_user_func_array('install_drupal', Array)
#25 /var/www/html/vendor/drush/drush/src/Commands/core/SiteInstallCommands.php(152): drush_op('install_drupal', Object(Composer\Autoload\ClassLoader), Array, Array)
#26 [internal function]: Drush\Commands\core\SiteInstallCommands->install('localgov', Array)
#27 /var/www/html/vendor/consolidation/annotated-command/src/CommandProcessor.php(257): call_user_func_array(Array, Array)
#28 /var/www/html/vendor/consolidation/annotated-command/src/CommandProcessor.php(212): Consolidation\AnnotatedCommand\CommandProcessor->runCommandCallback(Array, Object(Consolidation\AnnotatedCommand\CommandData))
#29 /var/www/html/vendor/consolidation/annotated-command/src/CommandProcessor.php(176): Consolidation\AnnotatedCommand\CommandProcessor->validateRunAndAlter(Array, Array, Object(Consolidation\AnnotatedCommand\CommandData))
#30 /var/www/html/vendor/consolidation/annotated-command/src/AnnotatedCommand.php(350): Consolidation\AnnotatedCommand\CommandProcessor->process(Object(Symfony\Component\Console\Output\ConsoleOutput), Array, Array, Object(Consolidation\AnnotatedCommand\CommandData))
#31 /var/www/html/vendor/symfony/console/Command/Command.php(255): Consolidation\AnnotatedCommand\AnnotatedCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#32 /var/www/html/vendor/symfony/console/Application.php(1027): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#33 /var/www/html/vendor/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand(Object(Consolidation\AnnotatedCommand\AnnotatedCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#34 /var/www/html/vendor/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#35 /var/www/html/vendor/drush/drush/src/Runtime/Runtime.php(124): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#36 /var/www/html/vendor/drush/drush/src/Runtime/Runtime.php(51): Drush\Runtime\Runtime->doRun(Array, Object(Symfony\Component\Console\Output\ConsoleOutput))
#37 /var/www/html/vendor/drush/drush/drush.php(77): Drush\Runtime\Runtime->run(Array)
#38 /var/www/html/vendor/drush/drush/drush(4): require('/var/www/html/v...')
#39 /var/www/html/bin/drush(120): include('/var/www/html/v...')
#40 {main}
TypeError: Drupal\localgov_directories\ConfigurationHelper::getIndex(): Return value must be of type Drupal\search_api\IndexInterface, null returned in Drupal\localgov_directories\ConfigurationHelper->getIndex() (line 128 of /var/www/html/web/modules/contrib/localgov_directories/src/ConfigurationHelper.php).
 [warning] Drush command terminated abnormally.
Failed to run drush si --existing-config: exit status 1
```

</p>
</details>

**Comment by siliconmeadow** [comment]
I will capture the output of what happens when I try to use the `localgov_directories_org` module at some stage. Need to step away from the computer for a while now.

**Comment by stephen-cox** [comment]
I have managed to reproduce this when enabling the Demo module after a site install, but not just enabling directories and search as mentioned above.

Verbose output showing the error looks like:

```
$ lando drush -vv si --existing-config
lando 12:05:18 VERBOSE ==> starting bootstrap at level engine... 
lando 12:05:18 VERBOSE ==> config bootstrap beginning... 
lando 12:05:18 VERBOSE ==> building proxy config... 
lando 12:05:18 VERBOSE ==> config bootstrap completed. 
lando 12:05:18 VERBOSE ==> tasks bootstrap beginning... 
lando 12:05:19 VERBOSE ==> tasks bootstrap completed. 
lando 12:05:19 VERBOSE ==> engine bootstrap beginning... 
lando 12:05:19 VERBOSE ==> engine bootstrap completed. 
lando 12:05:19 VERBOSE ==> bootstrap completed. 
lando 12:05:19 VERBOSE ==> docker-engine exists: true 
lando 12:05:19 VERBOSE ==> docker-compose exists: true 
 [info] Starting bootstrap to root
 [info] Drush bootstrap phase 1
 [info] Try to validate bootstrap phase 1
 [info] Try to validate bootstrap phase 1
 [info] Try to bootstrap at phase 1
 [info] Drush bootstrap phase: bootstrapDrupalRoot()
 [info] Change working directory to /app/web
 [info] Initialized Drupal 9.4.8 root directory at /app/web
 [info] Drush bootstrap phase: bootstrapDrupalSite()
 [info] Initialized Drupal site localgov-2.x.lndo.site at sites/default
 [info] Drush bootstrap phase: bootstrapDrupalConfiguration()
 [info] Executing: command -v mysql
 [info] Executing: mysql --defaults-file=/tmp/drush_xfjtVQ --database=database --host=database --port=3306 --silent -A < /tmp/drush_etD80Q

 You are about to:
 * DROP all tables in your 'database' database.

 Do you want to continue? (yes/no) [yes]:
 > lando 12:05:19 VERBOSE ==> checking docker version compatibility... 
                                                                       ^X^X^X^C
[stephen@laerates] [2.x → origin {8} U:1 ?:1099] ~/Dev/lando/localgovdrupal-2.x
$ ^C

[stephen@laerates] [2.x → origin {8} U:1 ?:1099] ~/Dev/lando/localgovdrupal-2.x
$ ^C

[stephen@laerates] [2.x → origin {8} U:1 ?:1099] ~/Dev/lando/localgovdrupal-2.x
$ lando drush -vv si --existing-config --yes
lando 12:05:28 VERBOSE ==> starting bootstrap at level engine... 
lando 12:05:28 VERBOSE ==> config bootstrap beginning... 
lando 12:05:28 VERBOSE ==> building proxy config... 
lando 12:05:28 VERBOSE ==> config bootstrap completed. 
lando 12:05:28 VERBOSE ==> tasks bootstrap beginning... 
lando 12:05:28 VERBOSE ==> tasks bootstrap completed. 
lando 12:05:28 VERBOSE ==> engine bootstrap beginning... 
lando 12:05:28 VERBOSE ==> engine bootstrap completed. 
lando 12:05:28 VERBOSE ==> bootstrap completed. 
lando 12:05:28 VERBOSE ==> docker-engine exists: true 
lando 12:05:28 VERBOSE ==> docker-compose exists: true 
 [info] Starting bootstrap to root
 [info] Drush bootstrap phase 1
 [info] Try to validate bootstrap phase 1
 [info] Try to validate bootstrap phase 1
 [info] Try to bootstrap at phase 1
 [info] Drush bootstrap phase: bootstrapDrupalRoot()
 [info] Change working directory to /app/web
 [info] Initialized Drupal 9.4.8 root directory at /app/web
 [info] Drush bootstrap phase: bootstrapDrupalSite()
 [info] Initialized Drupal site localgov-2.x.lndo.site at sites/default
 [info] Drush bootstrap phase: bootstrapDrupalConfiguration()
 [info] Executing: command -v mysql
 [info] Executing: mysql --defaults-file=/tmp/drush_wjMAfK --database=database --host=database --port=3306 --silent -A < /tmp/drush_gAwb7N

 You are about to:
 * DROP all tables in your 'database' database.

 // Do you want to continue?: yes.                                                                                      

 [info] Sites directory sites/default already exists - proceeding.
 [info] Executing: mysql --defaults-file=/tmp/drush_Cq9TsN --database=database --host=database --port=3306 --silent -A < /tmp/drush_oRs1NM
 [info] Executing: mysql --defaults-file=/tmp/drush_WJaGcO --database=database --host=database --port=3306 --silent -A < /tmp/drush_cxdEQM
 [info] Executing: mysql --defaults-file=/tmp/drush_mbJUgM --database=database --host=database --port=3306 --silent -A < /tmp/drush_pnDcDL
 [info] Installing from existing config at ../config/sync
 [notice] Starting Drupal installation. This takes a while.
lando 12:05:28 VERBOSE ==> checking docker version compatibility... 
                                                                     [notice] Performed install task: install_select_language
 [notice] Performed install task: install_select_profile
 [notice] Performed install task: install_load_profile
 [notice] Performed install task: install_verify_requirements
 [notice] Performed install task: install_verify_database_ready
 [info] mysql module installed.
 [info] system module installed.
 [info] user module installed.
 [notice] Performed install task: install_base_system
 [notice] Performed install task: install_bootstrap_full
 [info] automated_cron module installed.
 [info] config module installed.
 [info] dblog module installed.
 [info] dynamic_page_cache module installed.
 [info] field module installed.
 [info] help module installed.
 [info] localgov_admin_theme_improvements module installed.
 [info] localgov_menu_link_group module installed.
 [info] page_cache module installed.
 [info] update module installed.
 [info] file module installed.
 [info] filter module installed.
 [info] text module installed.
 [info] options module installed.
 [info] block module installed.
 [info] block_content module installed.
 [info] node module installed.
 [info] breakpoint module installed.
 [info] editor module installed.
 [info] ckeditor module installed.
 [info] workflows module installed.
 [info] content_moderation module installed.
 [info] contextual module installed.
 [info] datetime module installed.
 [info] datetime_range module installed.
 [info] layout_discovery module installed.
 [info] field_ui module installed.
 [info] history module installed.
 [info] taxonomy module installed.
 [info] image module installed.
 [info] link module installed.
 [info] media module installed.
 [info] views module installed.
 [info] media_library module installed.
 [info] menu_link_content module installed.
 [info] menu_ui module installed.
 [info] path_alias module installed.
 [info] path module installed.
 [info] quickedit module installed.
 [info] responsive_image module installed.
 [info] toolbar module installed.
 [info] telephone module installed.
 [info] views_ui module installed.
 [info] address module installed.
 [info] admin_toolbar module installed.
 [info] admin_toolbar_tools module installed.
 [info] condition_field module installed.
 [info] crop module installed.
 [info] date_recur module installed.
 [info] date_recur_modular module installed.
 [info] dbal module installed.
 [info] default_content module installed.
 [info] diff module installed.
 [info] dynamic_entity_reference module installed.
 [info] entity_browser module installed.
 [info] inline_entity_form module installed.
 [info] entity_browser_entity_form module installed.
 [info] entity_hierarchy module installed.
 [info] entity_hierarchy_breadcrumb module installed.
 [info] entity_reference_facet_link module installed.
 [info] entity_reference_revisions module installed.
 [info] entity_usage module installed.
 [info] facets module installed.
 [info] field_formatter_class module installed.
 [info] field_group module installed.
 [info] fontawesome module installed.
 [info] geocoder module installed.
 [info] geocoder_field module installed.
 [info] geofield module installed.
 [info] geocoder_geofield module installed.
 [info] geofield_map module installed.
 [info] geolocation module installed.
 [info] geolocation_google_maps module installed.
 [info] search_api module installed.
 [info] image_widget_crop module installed.
 [info] paragraphs module installed.
 [info] layout_paragraphs module installed.
 [info] paragraphs_library module installed.
 [info] leaflet module installed.
 [info] leaflet_views module installed.
 [info] link_attributes module installed.
 [info] linkit module installed.
 [info] localgov_alert_banner module installed.
 [info] media_library_edit module installed.
 [info] localgov_media module installed.
 [info] localgov_core module installed.
 [info] role_delegation module installed.
 [info] localgov_roles module installed.
 [info] token module installed.
 [info] pathauto module installed.
 [info] localgov_directories module installed.
 [info] search_api_db module installed.
 [info] localgov_directories_db module installed.
 [info] localgov_geo module installed.
 [info] localgov_geo_address module installed.
 [info] localgov_directories_location module installed.
 [info] localgov_directories_page module installed.
 [info] localgov_directories_venue module installed.
 [info] localgov_events module installed.
 [info] localgov_geo_area module installed.
 [info] localgov_guides module installed.
 [info] localgov_topics module installed.
 [info] search_api_autocomplete module installed.
 [info] metatag module installed.
 [info] schema_metatag module installed.
 [info] schema_article module installed.
 [info] localgov_news module installed.
 [info] localgov_search module installed.
 [info] localgov_search_db module installed.
 [info] localgov_services module installed.
 [info] office_hours module installed.
 [info] localgov_paragraphs module installed.
 [info] localgov_services_navigation module installed.
 [info] localgov_page_components module installed.
 [info] localgov_services_page module installed.
 [info] localgov_services_sublanding module installed.
 [info] localgov_services_landing module installed.
 [info] localgov_services_status module installed.
 [info] localgov_step_by_step module installed.
 [info] tablefield module installed.
 [info] viewsreference module installed.
 [info] localgov_homepage_paragraphs module installed.
 [info] localgov_subsites_paragraphs module installed.
 [info] localgov_subsites module installed.
 [info] preview_link module installed.
 [info] responsive_preview module installed.
 [info] scheduled_transitions module installed.

In EntityType.php line 877:
                                                                                      
  [LogicException]                                                                    
  Missing bundle entity, entity type node_type, entity id localgov_directories_page.  
                                                                                      

Exception trace:
  at /app/web/core/lib/Drupal/Core/Entity/EntityType.php:877
 Drupal\Core\Entity\EntityType->getBundleConfigDependency() at /app/web/core/modules/content_moderation/src/Plugin/WorkflowType/ContentModeration.php:241
 Drupal\content_moderation\Plugin\WorkflowType\ContentModeration->calculateDependencies() at /app/web/core/lib/Drupal/Core/Plugin/PluginDependencyTrait.php:71
 Drupal\Core\Config\Entity\ConfigEntityBase->getPluginDependencies() at /app/web/core/lib/Drupal/Core/Plugin/PluginDependencyTrait.php:89
 Drupal\Core\Config\Entity\ConfigEntityBase->calculatePluginDependencies() at /app/web/core/lib/Drupal/Core/Config/Entity/ConfigEntityBase.php:379
 Drupal\Core\Config\Entity\ConfigEntityBase->calculateDependencies() at /app/web/core/lib/Drupal/Core/Config/Entity/ConfigEntityBase.php:319
 Drupal\Core\Config\Entity\ConfigEntityBase->preSave() at /app/web/core/modules/workflows/src/Entity/Workflow.php:114
 Drupal\workflows\Entity\Workflow->preSave() at /app/web/core/lib/Drupal/Core/Entity/EntityStorageBase.php:562
 Drupal\Core\Entity\EntityStorageBase->doPreSave() at /app/web/core/lib/Drupal/Core/Entity/EntityStorageBase.php:517
 Drupal\Core\Entity\EntityStorageBase->save() at /app/web/core/lib/Drupal/Core/Config/Entity/ConfigEntityStorage.php:253
 Drupal\Core\Config\Entity\ConfigEntityStorage->save() at /app/web/core/lib/Drupal/Core/Entity/EntityBase.php:339
 Drupal\Core\Entity\EntityBase->save() at /app/web/core/lib/Drupal/Core/Config/Entity/ConfigEntityBase.php:607
 Drupal\Core\Config\Entity\ConfigEntityBase->save() at /app/web/modules/contrib/localgov_workflows/localgov_workflows.install:38
 localgov_workflows_install() at n/a:n/a
 call_user_func_array() at /app/web/core/lib/Drupal/Core/Extension/ModuleHandler.php:417
 Drupal\Core\Extension\ModuleHandler->invoke() at /app/web/core/lib/Drupal/Core/Extension/ModuleInstaller.php:357
 Drupal\Core\Extension\ModuleInstaller->install() at /app/web/core/lib/Drupal/Core/ProxyClass/Extension/ModuleInstaller.php:83
 Drupal\Core\ProxyClass\Extension\ModuleInstaller->install() at /app/web/core/lib/Drupal/Core/Config/ConfigImporter.php:817
 Drupal\Core\Config\ConfigImporter->processExtension() at /app/web/core/lib/Drupal/Core/Config/ConfigImporter.php:575
 Drupal\Core\Config\ConfigImporter->processExtensions() at /app/web/core/lib/Drupal/Core/Config/ConfigImporter.php:512
 Drupal\Core\Config\ConfigImporter->doSyncStep() at /app/web/core/lib/Drupal/Core/Config/Importer/ConfigImporterBatch.php:31
 Drupal\Core\Config\Importer\ConfigImporterBatch::process() at /app/web/core/includes/batch.inc:295
 _batch_process() at /app/web/core/includes/form.inc:955
 batch_process() at /app/web/core/includes/install.core.inc:653
 install_run_task() at /app/web/core/includes/install.core.inc:571
 install_run_tasks() at /app/web/core/includes/install.core.inc:119
 install_drupal() at /app/vendor/drush/drush/includes/drush.inc:129
 drush_call_user_func_array() at /app/vendor/drush/drush/includes/drush.inc:113
 drush_op() at /app/vendor/drush/drush/src/Commands/core/SiteInstallCommands.php:152
 Drush\Commands\core\SiteInstallCommands->install() at n/a:n/a
 call_user_func_array() at /app/vendor/consolidation/annotated-command/src/CommandProcessor.php:257
 Consolidation\AnnotatedCommand\CommandProcessor->runCommandCallback() at /app/vendor/consolidation/annotated-command/src/CommandProcessor.php:212
 Consolidation\AnnotatedCommand\CommandProcessor->validateRunAndAlter() at /app/vendor/consolidation/annotated-command/src/CommandProcessor.php:176
 Consolidation\AnnotatedCommand\CommandProcessor->process() at /app/vendor/consolidation/annotated-command/src/AnnotatedCommand.php:350
 Consolidation\AnnotatedCommand\AnnotatedCommand->execute() at /app/vendor/symfony/console/Command/Command.php:255
 Symfony\Component\Console\Command\Command->run() at /app/vendor/symfony/console/Application.php:1027
 Symfony\Component\Console\Application->doRunCommand() at /app/vendor/symfony/console/Application.php:273
 Symfony\Component\Console\Application->doRun() at /app/vendor/symfony/console/Application.php:149
 Symfony\Component\Console\Application->run() at /app/vendor/drush/drush/src/Runtime/Runtime.php:124
 Drush\Runtime\Runtime->doRun() at /app/vendor/drush/drush/src/Runtime/Runtime.php:51
 Drush\Runtime\Runtime->run() at /app/vendor/drush/drush/drush.php:77
 require() at /app/vendor/drush/drush/drush:4
 include() at /app/bin/drush:117
```

**Comment by stephen-cox** [comment]
From the stacktrace above, it looks like an issue with `localgov_workflows`

**Comment by siliconmeadow** [comment]
Ah, I had done this so many times and in verbose mode too. I remember seeing something to do with transitions and workflows in those earlier runs, but I'd been using config on one of the Essex sites that had quite a bit of variation from the initial installation. I figured if I was going to get help trying to solve the problem, I'd have to have a generic OOTB installation, plus I know that when troubleshooting something, it's best to start simplifying as soon as.

Back to verbose mode and looking at workflows then!
