### ISSUE TITLE
Error importing config when enabling locagov_directories_venue

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov_directories#259]
Reported by @chriswales95

CC @ekes 

## Steps to reproduce: 

```
lando drush si localgov -y
lando db-export test.sql
lando drush en localgov_directories_venue
lando drush cex
lando db-import test.sql.gz
lando drush cim 
```

## Expected result: 

clean import with localgov_directories_venue enabled.

## Actual result: 

``` [error]  TypeError: Drupal\localgov_directories\ConfigurationHelper::getIndex(): Return value must be of type Drupal\search_api\IndexInterface, null returned in Drupal\localgov_directories\ConfigurationHelper->getIndex() (line 128 of /app/web/modules/contrib/localgov_directories/src/ConfigurationHelper.php) #0 /app/web/modules/contrib/localgov_directories/src/ConfigurationHelper.php(197): Drupal\localgov_directories\ConfigurationHelper->getIndex()
#1 /app/web/modules/contrib/localgov_directories/localgov_directories.module(155): Drupal\localgov_directories\ConfigurationHelper->insertedTitleSortField(Object(Drupal\field\Entity\FieldConfig))
#2 [internal function]: localgov_directories_field_config_insert(Object(Drupal\field\Entity\FieldConfig))
#3 /app/web/core/lib/Drupal/Core/Extension/ModuleHandler.php(426): call_user_func_array(Object(Closure), Array)
#4 /app/web/core/lib/Drupal/Core/Extension/ModuleHandler.php(405): Drupal\Core\Extension\ModuleHandler->Drupal\Core\Extension\{closure}(Object(Closure), 'localgov_direct...')
#5 /app/web/core/lib/Drupal/Core/Extension/ModuleHandler.php(433): Drupal\Core\Extension\ModuleHandler->invokeAllWith('field_config_in...', Object(Closure))
#6 /app/web/core/lib/Drupal/Core/Config/Entity/ConfigEntityStorage.php(337): Drupal\Core\Extension\ModuleHandler->invokeAll('field_config_in...', Array)
#7 /app/web/core/lib/Drupal/Core/Entity/EntityStorageBase.php(598): Drupal\Core\Config\Entity\ConfigEntityStorage->invokeHook('insert', Object(Drupal\field\Entity\FieldConfig))
#8 /app/web/core/lib/Drupal/Core/Entity/EntityStorageBase.php(523): Drupal\Core\Entity\EntityStorageBase->doPostSave(Object(Drupal\field\Entity\FieldConfig), false)
#9 /app/web/core/lib/Drupal/Core/Config/Entity/ConfigEntityStorage.php(253): Drupal\Core\Entity\EntityStorageBase->save(Object(Drupal\field\Entity\FieldConfig))
#10 /app/web/core/lib/Drupal/Core/Entity/EntityBase.php(339): Drupal\Core\Config\Entity\ConfigEntityStorage->save(Object(Drupal\field\Entity\FieldConfig))
#11 /app/web/core/lib/Drupal/Core/Config/Entity/ConfigEntityBase.php(608): Drupal\Core\Entity\EntityBase->save()
#12 /app/web/core/lib/Drupal/Core/Config/Entity/ConfigEntityStorage.php(354): Drupal\Core\Config\Entity\ConfigEntityBase->save()
#13 /app/web/core/lib/Drupal/Core/Config/ConfigImporter.php(1001): Drupal\Core\Config\Entity\ConfigEntityStorage->importCreate('field.field.nod...', Object(Drupal\Core\Config\Config), Object(Drupal\Core\Config\Config))
#14 /app/web/core/lib/Drupal/Core/Config/ConfigImporter.php(787): Drupal\Core\Config\ConfigImporter->importInvokeOwner('', 'create', 'field.field.nod...')
#15 /app/web/core/lib/Drupal/Core/Config/ConfigImporter.php(608): Drupal\Core\Config\ConfigImporter->processConfiguration('', 'create', 'field.field.nod...')
#16 /app/web/core/lib/Drupal/Core/Config/ConfigImporter.php(512): Drupal\Core\Config\ConfigImporter->processConfigurations(Array)
#17 /app/vendor/drush/drush/src/Drupal/Commands/config/ConfigImportCommands.php(300): Drupal\Core\Config\ConfigImporter->doSyncStep('processConfigur...', Array)
#18 /app/vendor/drush/drush/includes/drush.inc(122): Drush\Drupal\Commands\config\ConfigImportCommands->doImport(Object(Drupal\Core\Config\StorageComparer))
#19 /app/vendor/drush/drush/includes/drush.inc(113): drush_call_user_func_array(Array, Array)
#20 /app/vendor/drush/drush/src/Drupal/Commands/config/ConfigImportCommands.php(271): drush_op(Array, Object(Drupal\Core\Config\StorageComparer))
#21 [internal function]: Drush\Drupal\Commands\config\ConfigImportCommands->import(Array)
#22 /app/vendor/consolidation/annotated-command/src/CommandProcessor.php(257): call_user_func_array(Array, Array)
#23 /app/vendor/consolidation/annotated-command/src/CommandProcessor.php(212): Consolidation\AnnotatedCommand\CommandProcessor->runCommandCallback(Array, Object(Consolidation\AnnotatedCommand\CommandData))
#24 /app/vendor/consolidation/annotated-command/src/CommandProcessor.php(176): Consolidation\AnnotatedCommand\CommandProcessor->validateRunAndAlter(Array, Array, Object(Consolidation\AnnotatedCommand\CommandData))
#25 /app/vendor/consolidation/annotated-command/src/AnnotatedCommand.php(390): Consolidation\AnnotatedCommand\CommandProcessor->process(Object(Symfony\Component\Console\Output\ConsoleOutput), Array, Array, Object(Consolidation\AnnotatedCommand\CommandData))
#26 /app/vendor/symfony/console/Command/Command.php(255): Consolidation\AnnotatedCommand\AnnotatedCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#27 /app/vendor/symfony/console/Application.php(1039): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#28 /app/vendor/symfony/console/Application.php(275): Symfony\Component\Console\Application->doRunCommand(Object(Consolidation\AnnotatedCommand\AnnotatedCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#29 /app/vendor/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#30 /app/vendor/drush/drush/src/Runtime/Runtime.php(124): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#31 /app/vendor/drush/drush/src/Runtime/Runtime.php(51): Drush\Runtime\Runtime->doRun(Array, Object(Symfony\Component\Console\Output\ConsoleOutput))
#32 /app/vendor/drush/drush/drush.php(77): Drush\Runtime\Runtime->run(Array)
#33 /app/vendor/drush/drush/drush(4): require('/app/vendor/dru...')
#34 /app/bin/drush(117): include('/app/vendor/dru...')
#35 {main}. 
TypeError: Drupal\localgov_directories\ConfigurationHelper::getIndex(): Return value must be of type Drupal\search_api\IndexInterface, null returned in /app/web/modules/contrib/localgov_directories/src/ConfigurationHelper.php on line 128 #0 /app/web/modules/contrib/localgov_directories/src/ConfigurationHelper.php(197): Drupal\localgov_directories\ConfigurationHelper->getIndex()
#1 /app/web/modules/contrib/localgov_directories/localgov_directories.module(155): Drupal\localgov_directories\ConfigurationHelper->insertedTitleSortField(Object(Drupal\field\Entity\FieldConfig))
#2 [internal function]: localgov_directories_field_config_insert(Object(Drupal\field\Entity\FieldConfig))
#3 /app/web/core/lib/Drupal/Core/Extension/ModuleHandler.php(426): call_user_func_array(Object(Closure), Array)
#4 /app/web/core/lib/Drupal/Core/Extension/ModuleHandler.php(405): Drupal\Core\Extension\ModuleHandler->Drupal\Core\Extension\{closure}(Object(Closure), 'localgov_direct...')
#5 /app/web/core/lib/Drupal/Core/Extension/ModuleHandler.php(433): Drupal\Core\Extension\ModuleHandler->invokeAllWith('field_config_in...', Object(Closure))
#6 /app/web/core/lib/Drupal/Core/Config/Entity/ConfigEntityStorage.php(337): Drupal\Core\Extension\ModuleHandler->invokeAll('field_config_in...', Array)
#7 /app/web/core/lib/Drupal/Core/Entity/EntityStorageBase.php(598): Drupal\Core\Config\Entity\ConfigEntityStorage->invokeHook('insert', Object(Drupal\field\Entity\FieldConfig))
#8 /app/web/core/lib/Drupal/Core/Entity/EntityStorageBase.php(523): Drupal\Core\Entity\EntityStorageBase->doPostSave(Object(Drupal\field\Entity\FieldConfig), false)
#9 /app/web/core/lib/Drupal/Core/Config/Entity/ConfigEntityStorage.php(253): Drupal\Core\Entity\EntityStorageBase->save(Object(Drupal\field\Entity\FieldConfig))
#10 /app/web/core/lib/Drupal/Core/Entity/EntityBase.php(339): Drupal\Core\Config\Entity\ConfigEntityStorage->save(Object(Drupal\field\Entity\FieldConfig))
#11 /app/web/core/lib/Drupal/Core/Config/Entity/ConfigEntityBase.php(608): Drupal\Core\Entity\EntityBase->save()
#12 /app/web/core/lib/Drupal/Core/Config/Entity/ConfigEntityStorage.php(354): Drupal\Core\Config\Entity\ConfigEntityBase->save()
#13 /app/web/core/lib/Drupal/Core/Config/ConfigImporter.php(1001): Drupal\Core\Config\Entity\ConfigEntityStorage->importCreate('field.field.nod...', Object(Drupal\Core\Config\Config), Object(Drupal\Core\Config\Config))
#14 /app/web/core/lib/Drupal/Core/Config/ConfigImporter.php(787): Drupal\Core\Config\ConfigImporter->importInvokeOwner('', 'create', 'field.field.nod...')
#15 /app/web/core/lib/Drupal/Core/Config/ConfigImporter.php(608): Drupal\Core\Config\ConfigImporter->processConfiguration('', 'create', 'field.field.nod...')
#16 /app/web/core/lib/Drupal/Core/Config/ConfigImporter.php(512): Drupal\Core\Config\ConfigImporter->processConfigurations(Array)
#17 /app/vendor/drush/drush/src/Drupal/Commands/config/ConfigImportCommands.php(300): Drupal\Core\Config\ConfigImporter->doSyncStep('processConfigur...', Array)
#18 /app/vendor/drush/drush/includes/drush.inc(122): Drush\Drupal\Commands\config\ConfigImportCommands->doImport(Object(Drupal\Core\Config\StorageComparer))
#19 /app/vendor/drush/drush/includes/drush.inc(113): drush_call_user_func_array(Array, Array)
#20 /app/vendor/drush/drush/src/Drupal/Commands/config/ConfigImportCommands.php(271): drush_op(Array, Object(Drupal\Core\Config\StorageComparer))
#21 [internal function]: Drush\Drupal\Commands\config\ConfigImportCommands->import(Array)
#22 /app/vendor/consolidation/annotated-command/src/CommandProcessor.php(257): call_user_func_array(Array, Array)
#23 /app/vendor/consolidation/annotated-command/src/CommandProcessor.php(212): Consolidation\AnnotatedCommand\CommandProcessor->runCommandCallback(Array, Object(Consolidation\AnnotatedCommand\CommandData))
#24 /app/vendor/consolidation/annotated-command/src/CommandProcessor.php(176): Consolidation\AnnotatedCommand\CommandProcessor->validateRunAndAlter(Array, Array, Object(Consolidation\AnnotatedCommand\CommandData))
#25 /app/vendor/consolidation/annotated-command/src/AnnotatedCommand.php(390): Consolidation\AnnotatedCommand\CommandProcessor->process(Object(Symfony\Component\Console\Output\ConsoleOutput), Array, Array, Object(Consolidation\AnnotatedCommand\CommandData))
#26 /app/vendor/symfony/console/Command/Command.php(255): Consolidation\AnnotatedCommand\AnnotatedCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#27 /app/vendor/symfony/console/Application.php(1039): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#28 /app/vendor/symfony/console/Application.php(275): Symfony\Component\Console\Application->doRunCommand(Object(Consolidation\AnnotatedCommand\AnnotatedCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#29 /app/vendor/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#30 /app/vendor/drush/drush/src/Runtime/Runtime.php(124): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#31 /app/vendor/drush/drush/src/Runtime/Runtime.php(51): Drush\Runtime\Runtime->doRun(Array, Object(Symfony\Component\Console\Output\ConsoleOutput))
#32 /app/vendor/drush/drush/drush.php(77): Drush\Runtime\Runtime->run(Array)
#33 /app/vendor/drush/drush/drush(4): require('/app/vendor/dru...')
#34 /app/bin/drush(117): include('/app/vendor/dru...')
#35 {main}
TypeError: Drupal\localgov_directories\ConfigurationHelper::getIndex(): Return value must be of type Drupal\search_api\IndexInterface, null returned in Drupal\localgov_directories\ConfigurationHelper->getIndex() (line 128 of /app/web/modules/contrib/localgov_directories/src/ConfigurationHelper.php).
 [warning] Drush command terminated abnormally.

**Comment by chriswales95** [comment]
Thanks for opening this issue @finnlewis. Will look into as well when I have the chance!

**Comment by ekes** [comment]
`/app/web/modules/contrib/localgov_directories/localgov_directories.module(155)`

Is acting on the addition of the title sort field to an entity. This kindly updates the configuration of the search index to use the field.

`TypeError: Drupal\localgov_directories\ConfigurationHelper::getIndex() Return value must be of type Drupal\search_api\IndexInterface, null returned`

The signature is https://github.com/localgovdrupal/localgov_directories/blob/2.x/src/ConfigurationHelper.php#L127 such that it must always return an Index. But when it's doing that there is no index. All the calls to this method are however

`if ($index = $this->getIndex())`

checking to see if one is returned. So it's just that the signature is wrong. It is allowed to return `NULL`. Let's get this fixed.
